# Spanish translations for PROJECT.
# Copyright (C) 2019 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2019.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2019-04-22 13:00+0500\n"
"PO-Revision-Date: 2019-04-22 13:00+0500\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: es\n"
"Language-Team: es <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.6.0\n"

#: app/api/v1/requests/args_validation.py:37
#, python-format
msgid "imei too short, should contain at least %(min)s characters"
msgstr "imei demasiado corto, debe contener al menos %(min)s caracteres"

#: app/api/v1/requests/args_validation.py:39
#, python-format
msgid "imei too long, cannot contain more than %(max)s characters"
msgstr "Imei demasiado largo, no puede contener más de %(max)s caracteres"

#: app/api/v1/requests/args_validation.py:41
msgid "invalid imei"
msgstr "imei inválido"

#: app/api/v1/requests/args_validation.py:48
msgid "invalid msisdn"
msgstr "msisdn inválido"

#: app/api/v1/resources/admin.py:69
msgid "Failed to retrieve IMEI response from core system."
msgstr "Error al recuperar la respuesta IMEI del sistema central."

#: app/api/v1/resources/admin.py:83
msgid "Error generating IMEI response. Check dirbs core url."
msgstr "Error al generar la respuesta IMEI. Verifique la URL del núcleo de Dirbs."

#: app/api/v1/resources/admin.py:143
msgid "Error generating MSISDN response. Check dirbs core url."
msgstr "Error al generar la respuesta de MSISDN. Verifique la URL del núcleo de Dirbs."

#: app/api/v1/resources/case.py:56 app/api/v1/resources/case.py:124
#: app/api/v1/resources/case.py:173 app/api/v1/resources/case.py:389
msgid "Case not found"
msgstr "Caso no encontrado"

#: app/api/v1/resources/case.py:76
msgid ""
"Error retrieving case results. Please check tracking id or database "
"connection."
msgstr "Error al recuperar los resultados del caso. Por favor, compruebe el ID de seguimiento o la base de datos conexión."

#: app/api/v1/resources/case.py:93 app/api/v1/resources/case.py:374
msgid "Case updation not allowed in this status"
msgstr "Actualización de caso no permitida en este estado"

#: app/api/v1/resources/case.py:103 app/api/v1/resources/case.py:326
msgid "Enter at least one optional field with full name in personal details."
msgstr "Ingrese al menos un campo opcional con nombre completo en los datos personales."

#: app/api/v1/resources/case.py:113
msgid "Case updated successfully"
msgstr "Caso actualizado con éxito"

#: app/api/v1/resources/case.py:134
msgid "Case update failed!"
msgstr "Falló la actualización del caso!"

#: app/api/v1/resources/case.py:150
msgid ""
"Unable to update case status. Either Blocking is disabled or case has "
"already been recovered."
msgstr "No se puede actualizar el estado del caso. O el bloqueo está deshabilitado o el caso haya ha sido recuperado."

#: app/api/v1/resources/case.py:158
msgid "Case already has the same status."
msgstr "El caso ya tiene el mismo estado."

#: app/api/v1/resources/case.py:165 app/api/v1/resources/case.py:381
msgid "Case status updated"
msgstr "Estado del caso actualizado"

#: app/api/v1/resources/case.py:183
msgid "Case status update failed!"
msgstr "Falló la actualización del estado del caso!"

#: app/api/v1/resources/case.py:335
msgid "case successfully added"
msgstr "caso agregado exitosamente"

#: app/api/v1/resources/case.py:344 app/api/v1/resources/case.py:355
msgid "case addition failed"
msgstr "la adición del caso falló"

#: app/api/v1/resources/case.py:399
msgid "Update of case information failed!"
msgstr "La actualización de la información del caso falló!"

#: app/api/v1/resources/common.py:40
msgid "Welcome to LSDS"
msgstr "Bienvenido a LSDS"

#: app/api/v1/resources/common.py:57
msgid "CORE connected successfully."
msgstr "CORE conectado con éxito."

#: app/api/v1/resources/common.py:61 app/api/v1/resources/common.py:65
msgid "CORE connection failed."
msgstr "La conexión CORE ha fallado."

#: app/api/v1/resources/common.py:69
msgid "Database connected successfully"
msgstr "Base de datos conectada correctamente"

#: app/api/v1/resources/common.py:71
msgid "Database connection failed"
msgstr "Falló la conexión de la base de datos"

#: app/api/v1/resources/search.py:142
msgid "service unavailable"
msgstr "Servicio no disponible"

#: app/api/v1/resources/system.py:57 app/api/v1/resources/system.py:82
msgid "Database connectivity error. Please check connection parameters."
msgstr "Error de conectividad de la base de datos. Por favor, compruebe los parámetros de conexión."

#: app/api/v1/schema/validations.py:11
msgid "name should contain more than one character"
msgstr "el nombre debe contener más de un carácter"

#: app/api/v1/schema/validations.py:13
msgid "name cannot contain more than 1000 characters"
msgstr "el nombre debe contener más de un carácter"

#: app/api/v1/schema/validations.py:15
msgid "Name cannot contain invalid characters"
msgstr "El nombre no puede contener caracteres inválidos"

#: app/api/v1/schema/validations.py:22
msgid "Comment should contain more than one character"
msgstr "El comentario debe contener más de un carácter"

#: app/api/v1/schema/validations.py:24
msgid "Comment cannot contain more than 1000 characters"
msgstr "El comentario no puede contener más de 1000 caracteres"

#: app/api/v1/schema/validations.py:26
msgid "Comment cannot have invalid characters"
msgstr "El comentario no puede tener caracteres inválidos"

#: app/api/v1/schema/validations.py:33
msgid "Alternate phone number is invalid."
msgstr "El número de teléfono alternativo no es válido."

#: app/api/v1/schema/validations.py:40
msgid "Invalid date format"
msgstr "Formato de fecha no válido"

#: app/api/v1/schema/validations.py:49
#, python-format
msgid "IMEI too short, should contain at least %(min)s characters"
msgstr "IMEI demasiado corto, debe contener al menos %(min)s caracteres"

#: app/api/v1/schema/validations.py:51
#, python-format
msgid "IMEI too long, cannot contain more than %(max)s characters"
msgstr "IMEI demasiado largo, no puede contener más de %(max)s caracteres"

#: app/api/v1/schema/validations.py:53
msgid "IMEI is invalid."
msgstr "IMEI no es válido."

#: app/api/v1/schema/validations.py:60
msgid "MSISDN is invalid."
msgstr "MSISDN no es válido."

#: app/api/v1/schema/validations.py:68
#, python-format
msgid "Government Identification Number must contain %(range)s digits"
msgstr "El número de identificación del gobierno debe contener los dígitos de %(range)s"

#: app/api/v1/schema/validations.py:74
#, python-format
msgid "%(field)s should contain at least %(min)s character"
msgstr "%(field)s debe contener al menos %(min)s carácter"

#: app/api/v1/schema/validations.py:76
#, python-format
msgid "%(field)s cannot contain more than %(max)s characters"
msgstr "%(field)s no puede contener más de %(max)s caracteres"

msgid "PENDING"
msgstr "PENDIENTE"

msgid "RECOVERED"
msgstr "RECUPERADO"

msgid "BLOCKED"
msgstr "OBSTRUIDO"

msgid "LOST"
msgstr "PERDIÓ"

msgid "STOLEN"
msgstr "ROBADO"

msgid "System cannot accept duplicate Values"
msgstr "El sistema no puede aceptar valores duplicados"

msgid "Value is invalid. Does not match the selected language or invalid format."
msgstr "El valor no es válido. No coincide con el idioma seleccionado o el formato no válido."



